title: WAFR 2026
description: "Website of the 2026 World Symposium on the Algorithmic Foundations of Robotics (WAFR)."

theme: minima

header_pages:
  - info.md
  - program.md
  - venue.md
  - registration.md
  - committee.md
